name: CI-CD
# .....
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.generate_tag.outputs.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests
        run: mvn test

      - name: Build JAR
        run: mvn clean package

      - name: Generate Tag from SHA
        id: generate_tag
        run: echo "sha=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api_java_spring:${{ steps.generate_tag.outputs.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api_java_spring:${{ steps.generate_tag.outputs.sha }}

  deploy:
    name: Deploy on AWS EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Criar arquivo da chave privada
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Testar conex√£o SSH
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} "echo 'SSH OK from GitHub Actions!'"

      - name: Copiar docker-compose.prod.yml para o servidor
        run: |
          scp -i ~/.ssh/id_rsa docker-compose.prod.yml ubuntu@${{ secrets.SSH_HOST }}:~/docker-compose.prod.yml

      - name: Executar deploy no servidor
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~
            rm -f .env
            touch .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            echo "DOCKER_IMAGE_TAG=${{ needs.build.outputs.docker_tag }}" >> .env

            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker compose -f docker-compose.prod.yml up -d
            docker container prune -f
            docker image prune -f
          EOF
