name: Test SSH Only

on:
  workflow_dispatch:  # você dispara manualmente

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH via appleboy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 54.207.191.95                 # força o IP direto
          username: ubuntu                    # força o usuário direto
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }} # a MESMA chave que vc testou localmente
          debug: true
          script: |
            whoami
            hostname
            echo "Consegui logar na EC2 via GitHub Actions!"
